### ISSUE TITLE
Confusing error message with `bind:` on invalid property

### ISSUE THREAD

**Issue by btakita** [rollup/rollup-plugin-svelte#28]
`<input type="text" bind:newField />`

Results in the error:

```
TypeError: Cannot read property 'start' of undefined
    at error (/home/user/project/node_modules/rollup/dist/rollup.js:224:15)
    at /home/user/project/node_modules/rollup/dist/rollup.js:17213:17
    at <anonymous>
```

**Comment by Rich-Harris** [comment]
Can you give this a whirl with `svelte@1.60` please? I have a hunch this may be fixed now
