### ISSUE TITLE
Error: Unrecognized option 'onwarn' rears its ugly head once more

### ISSUE THREAD

**Issue by saabi** [rollup/rollup-plugin-svelte#50]
It shows up when trying to compile sveltejs/svelte-subdivide/pull/23

```
[!] (svelte plugin) Error: Unrecognized option 'onwarn'
src\Subdivide.svelte
Error: Unrecognized option 'onwarn'
    at Object.keys.forEach.key (I:\Work\repos\svelte-subdivide\node_modules\svelte\compiler.js:23829:20)
    at Array.forEach (<anonymous>)
    at validate_options (I:\Work\repos\svelte-subdivide\node_modules\svelte\compiler.js:23823:27)
    at compile (I:\Work\repos\svelte-subdivide\node_modules\svelte\compiler.js:23865:6)
    at preprocessPromise.then.code (I:\Work\repos\svelte-subdivide\node_modules\rollup-plugin-svelte\index.js:221:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

```
  "devDependencies": {
    "port-authority": "^1.0.3",
    "puppeteer": "^1.2.0",
    "rollup": "^1.6.0",
    "rollup-plugin-commonjs": "^9.1.0",
    "rollup-plugin-node-resolve": "^4.0.1",
    "rollup-plugin-svelte": "^5.0.3",
    "serve-handler": "^5.0.8",
    "svelte": "^3.0.0-beta.15",
    "tap-diff": "^0.1.1",
    "tap-dot": "^2.0.0",
    "tape-modern": "^1.0.0"
  }
```

**Comment by saabi** [comment]
Deleting node_modules and the npm lock file fixed it.
