### ISSUE TITLE
create_slot is not exported error when importing components from npm package

### ISSUE THREAD

**Issue by jz222** [rollup/rollup-plugin-svelte#68]
Hi, I'm working on an npm package that contains common UI elements that I repeatedly use in my projects. I now want to import these elements from my npm package in a different project, which leads to the following error:

```
Error: 'create_slot' is not exported by ../project-b/node_modules/svelte/internal/index.mjs
at error (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:10151:30)
at Module.error (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:14137:9)
at handleMissingExport (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:14056:21)
at Module.traceVariable (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:14448:17)
at ModuleScope.findVariable (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:13146:39)
at FunctionScope.findVariable (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:2981:38)
at ChildScope.findVariable (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:2981:38)
at Identifier$1.bind (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:9217:40)
at CallExpression$1.bind (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:7969:23)
at CallExpression$1.bind (/Users/user/dev/project-a/node_modules/rollup/dist/rollup.js:11093:15)
```

`project-a` is the project that should import the UI elements from `project-b`. The rollup config of `project-a` looks like this:

```javascript
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

export default {
    input: 'src/main.js',
    output: {
        sourcemap: true,
        format: 'iife',
        name: 'app',
        file: 'public/bundle.js'
    },
    plugins: [
        svelte({
            dev: !production,
            css: css => {
                css.write('public/bundle.css');
            }
        }),
        
        babel({
            extensions: [ ".js", ".mjs", ".html", ".svelte" ]
        }),
        
        resolve(),
        commonjs(),
        
        !production && livereload('public'),
        
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
};
```

In `project-a` I import an element from `project-b` like shown below.

```javascript
<script>
    import { Column } from 'project-b';
</script>
```

In `project-b` I added `"svelte": "index.js"` to my package.json. The corresponding `index.js` has the following content.

`export { default as Column } from './src/layout/column.svelte';`

The `column.svelte` component looks like this:

```HTML
<script>
    export let layout = "standard";
    export let width = 1;
</script>

<style>
    .column-narrow,
    .column-standard {
        -ms-flex: auto;
        width: 0;
        position: relative;
        box-sizing: border-box;
        border: 1px solid;
        background: red;
    }

    @media(max-width: 555px) {
        .column-narrow {
            flex-basis: 100% !important;
        }
    }
</style>

<div style="flex-basis: {(100 / 12) * width}%" class="column-{layout}">
    <slot />
</div>
```

What can I do to import and use the components from `project-b` in `project-a`? Thanks for the help.

**Comment by sw-yx** [comment]
what does the published component look like? where do you differ from https://github.com/sveltejs/component-template?
